services:
  - type: web
    name: ai-real-estate
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DATABASE_URL
        fromDatabase:
          name: ai_real_estate_db
          property: connectionString

databases:
  - name: ai_real_estate_db
    plan: free
    ipAllowList: []
